---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark-session-operator.fullname" . }}-manager
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spark-session-operator.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "spark-session-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-session-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-session-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "spark-session-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
