{{- if .Values.gateway.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spark-session-operator.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.gateway.ingressClassName }}
  rules:
  - host: {{ .Values.gateway.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "spark-session-operator.fullname" . }}-proxy
            port:
              number: 8080
{{- end }}
