apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-session-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
