apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-session-operator.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: gateway
  - name: thrift-proxy
    port: 10009
    protocol: TCP
    targetPort: thrift-proxy
  - name: connect-proxy
    port: 15002
    protocol: TCP
    targetPort: connect-proxy
  selector:
    {{- include "spark-session-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-session-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-session-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "spark-session-operator.selectorLabels" . | nindent 4 }}
